environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "10"
    - nodejs_version: "11"
    - nodejs_version: ""

cache:
  - ./node_modules

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g yarn
  - yarn install --frozen-lockfile

build: off

test_script:
  - echo Hello world!
